export const SITE_CONFIG = {
  name: 'DENEB UI',
  shortName: 'DENEB UI',
  title: 'DENEB UI — Visual-First React Framework & Celestial Storefront Suite',
  description:
    'A visual-first React component ecosystem and storefront authoring suite, developed in collaboration with FIVORA. Featuring shadcn-style unopinionated primitives, smart commerce actions, live dynamic business hours, WhatsApp checkout, and instant CLI scaffolding.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://deneb-ui.vercel.app',
  ogImage: '/og-image.png',
  creator: 'DENEB UI & FIVORA',
  publisher: 'DENEB UI',
  authors: [
    { name: 'Chamika Gayashan', url: 'https://github.com/chamikathereal' },
    { name: 'FIVORA Core Team', url: 'https://fivora.com' },
  ],
  links: {
    github: 'https://github.com/chamikathereal/ui',
    twitter: 'https://x.com',
    docs: '/docs/introduction',
  },
  keywords: [
    'React component library',
    'DENEB UI',
    'visual-first React components',
    'shadcn UI alternatives',
    'e-commerce React components',
    'storefront UI framework',
    'Tailwind CSS primitives',
    'headless commerce UI',
    'Fivora storefront components',
    'WhatsApp button React',
    'live business hours widget',
    'Google feedback widget React',
    'product card React component',
    'product detail React',
    'cart drawer component',
    'responsive commerce design',
    'Next.js component library',
    'React 19 UI kit',
    'celestial dark mode',
    'accessible React primitives',
  ],
};
