import React from 'react';
import { ComponentDocClient } from '@/components/docs/ComponentDocClient';

export const COMPONENT_SLUGS = [
  'button',
  'card',
  'badge',
  'typography',
  'dialog',
  'grid',
  'image',
  'contact-actions',
  'whatsapp-button',
  'phone-button',
  'email-button',
  'floating-contact-widget',
  'location-card',
  'location-link',
  'map-embed',
  'address',
  'business-hours',
  'social-links',
  'social-button',
  'hero',
  'product-card',
  'product-detail',
  'product-quickview',
  'product-grid',
  'cart-drawer',
  'filter-sidebar',
  'customer-reviews',
  'trust-badges',
  'sticky-mobile-bar',
  'service-card',
  'pricing-card',
  'testimonial-card',
  'faq-accordion',
  'announcement-bar',
  'category-pills',
  'contact-form',
  'navbar',
  'footer',
  'site-data-provider',
  'theme-styles',
];

export function generateStaticParams() {
  return [
    { slug: 'button' },
    { slug: 'card' },
    { slug: 'badge' },
    { slug: 'contact-actions' },
    { slug: 'whatsapp-button' },
    { slug: 'phone-button' },
    { slug: 'email-button' },
    { slug: 'floating-contact-widget' },
    { slug: 'business-hours' },
    { slug: 'location-card' },
    { slug: 'location-link' },
    { slug: 'map-embed' },
    { slug: 'address' },
    { slug: 'social-links' },
    { slug: 'social-button' },
    { slug: 'hero' },
    { slug: 'cart-drawer' },
    { slug: 'filter-sidebar' },
    { slug: 'product-detail' },
    { slug: 'product-quickview' },
    { slug: 'product-grid' },
    { slug: 'product-card' },
    { slug: 'customer-reviews' },
    { slug: 'trust-badges' },
    { slug: 'sticky-mobile-bar' },
    { slug: 'announcement-bar' },
    { slug: 'category-pills' },
    { slug: 'pricing-card' },
    { slug: 'testimonial-card' },
    { slug: 'service-card' },
    { slug: 'faq-accordion' },
    { slug: 'contact-form' },
    { slug: 'navbar' },
    { slug: 'footer' },
    { slug: 'dialog' },
    { slug: 'typography' },
    { slug: 'grid' },
    { slug: 'image' },
    { slug: 'google-feedback' },
    { slug: 'testimonial-section' },
    { slug: 'map' },
  ];
}

export default async function ComponentPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  return <ComponentDocClient slug={slug} />;
}
