// Auto-generated pure server/client safe metadata for DENEB UI components
export interface ComponentMeta {
  slug: string;
  title: string;
  description: string;
  category: string;
  keywords: string[];
}

export const COMPONENT_SLUGS: string[] = [
  'button',
  'card',
  'badge',
  'typography',
  'dialog',
  'grid',
  'image',
  'contact-actions',
  'whatsapp-button',
  'phone-button',
  'email-button',
  'floating-contact-widget',
  'location-card',
  'location-link',
  'map-embed',
  'address',
  'business-hours',
  'social-links',
  'social-button',
  'hero',
  'service-card',
  'pricing-card',
  'testimonial-card',
  'faq-accordion',
  'announcement-bar',
  'category-pills',
  'contact-form',
  'navbar',
  'footer',
  'site-data-provider',
  'theme-styles',
  'use-products',
  'use-site-api',
  'use-site-catalog',
  'product-detail',
  'platform-product-detail',
  'product-quickview',
  'product-grid',
  'customer-reviews',
  'trust-badges',
  'sticky-mobile-bar',
  'filter-sidebar',
  'google-feedback',
  'testimonial-section',
  'map',
  'product-card',
  'cart-drawer',
  'editable-section',
  'section',
];

export const COMPONENT_META: Record<string, ComponentMeta> = {
  'button': {
    slug: 'button',
    title: "Button",
    description: "An interactive button primitive with celestial glows, glassmorphic variants, and visual editing support.",
    category: "Core Primitives",
    keywords: ["Button","Button component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'card': {
    slug: 'card',
    title: "Card",
    description: "A versatile container card with obsidian glass styling, luminous borders, and structured content slots.",
    category: "Core Primitives",
    keywords: ["Card","Card component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'badge': {
    slug: 'badge',
    title: "Badge",
    description: "Status pills and indicator tags with celestial starlight glows.",
    category: "Core Primitives",
    keywords: ["Badge","Badge component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'typography': {
    slug: 'typography',
    title: "Typography",
    description: "Semantic text primitives (Heading, Paragraph, Text, Quote) linked directly to Fivora theme font tokens.",
    category: "Core Primitives",
    keywords: ["Typography","Typography component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'dialog': {
    slug: 'dialog',
    title: "Dialog",
    description: "Accessible modal dialog with backdrop blur, keyboard ESC dismissal, sizing tiers, and live visual editing.",
    category: "Core Primitives",
    keywords: ["Dialog","Dialog component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'grid': {
    slug: 'grid',
    title: "Grid & Box",
    description: "Layout containers featuring auto-balancing columns (minCardWidth), custom spacing tokens, and flex alignment.",
    category: "Core Primitives",
    keywords: ["Grid & Box","Grid & Box component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'image': {
    slug: 'image',
    title: "Image",
    description: "Responsive storefront image component supporting preset aspect ratios, border radii, and visual editing upload triggers.",
    category: "Core Primitives",
    keywords: ["Image","Image component","React component","Tailwind CSS","Deneb UI","Core Primitives","visual-first","storefront UI","headless e-commerce"],
  },
  'contact-actions': {
    slug: 'contact-actions',
    title: "ContactActions",
    description: "Smart multi-channel container that automatically inspects merchant phone, WhatsApp, and email, rendering active triggers with zero template changes.",
    category: "Smart Commerce Actions",
    keywords: ["ContactActions","ContactActions component","React component","Tailwind CSS","Deneb UI","Smart Commerce Actions","visual-first","storefront UI","headless e-commerce"],
  },
  'whatsapp-button': {
    slug: 'whatsapp-button',
    title: "WhatsAppButton",
    description: "One-click WhatsApp click-to-chat button with built-in official SVG icon and direct link resolution.",
    category: "Smart Commerce Actions",
    keywords: ["WhatsAppButton","WhatsAppButton component","React component","Tailwind CSS","Deneb UI","Smart Commerce Actions","visual-first","storefront UI","headless e-commerce"],
  },
  'phone-button': {
    slug: 'phone-button',
    title: "PhoneButton",
    description: "Direct telephone dialing trigger (tel:) with formatted phone display and official telephone icon.",
    category: "Smart Commerce Actions",
    keywords: ["PhoneButton","PhoneButton component","React component","Tailwind CSS","Deneb UI","Smart Commerce Actions","visual-first","storefront UI","headless e-commerce"],
  },
  'email-button': {
    slug: 'email-button',
    title: "EmailButton",
    description: "Direct mailto: action button with optional prefilled subject line and envelope icon.",
    category: "Smart Commerce Actions",
    keywords: ["EmailButton","EmailButton component","React component","Tailwind CSS","Deneb UI","Smart Commerce Actions","visual-first","storefront UI","headless e-commerce"],
  },
  'floating-contact-widget': {
    slug: 'floating-contact-widget',
    title: "FloatingContactWidget",
    description: "Sticky corner floating action button that expands into a speed-dial menu for WhatsApp, phone, and email inquiries.",
    category: "Smart Commerce Actions",
    keywords: ["FloatingContactWidget","FloatingContactWidget component","React component","Tailwind CSS","Deneb UI","Smart Commerce Actions","visual-first","storefront UI","headless e-commerce"],
  },
  'location-card': {
    slug: 'location-card',
    title: "LocationCard",
    description: "Storefront location card with formatted address, map pin, and direct Google Maps directions trigger.",
    category: "Location & Navigation",
    keywords: ["LocationCard","LocationCard component","React component","Tailwind CSS","Deneb UI","Location & Navigation","visual-first","storefront UI","headless e-commerce"],
  },
  'location-link': {
    slug: 'location-link',
    title: "LocationLink",
    description: "Inline clickable text link opening the physical business address in Google Maps or Apple Maps.",
    category: "Location & Navigation",
    keywords: ["LocationLink","LocationLink component","React component","Tailwind CSS","Deneb UI","Location & Navigation","visual-first","storefront UI","headless e-commerce"],
  },
  'map-embed': {
    slug: 'map-embed',
    title: "MapEmbed",
    description: "Safe responsive Google Maps embed iframe with automatic fallback link when embed URL is not yet configured.",
    category: "Location & Navigation",
    keywords: ["MapEmbed","MapEmbed component","React component","Tailwind CSS","Deneb UI","Location & Navigation","visual-first","storefront UI","headless e-commerce"],
  },
  'address': {
    slug: 'address',
    title: "Address",
    description: "Semantic, formatted HTML address block with microdata schema readiness and visual editing attributes.",
    category: "Location & Navigation",
    keywords: ["Address","Address component","React component","Tailwind CSS","Deneb UI","Location & Navigation","visual-first","storefront UI","headless e-commerce"],
  },
  'business-hours': {
    slug: 'business-hours',
    title: "BusinessHours",
    description: "Weekly schedule renderer featuring live dynamic calculation of Open Now and Closed status badges based on visitor local time.",
    category: "Social & Business",
    keywords: ["BusinessHours","BusinessHours component","React component","Tailwind CSS","Deneb UI","Social & Business","visual-first","storefront UI","headless e-commerce"],
  },
  'social-links': {
    slug: 'social-links',
    title: "SocialLinks",
    description: "Smart social media channel container with branded icons (Instagram, Facebook, TikTok, YouTube, X, GitHub).",
    category: "Social & Business",
    keywords: ["SocialLinks","SocialLinks component","React component","Tailwind CSS","Deneb UI","Social & Business","visual-first","storefront UI","headless e-commerce"],
  },
  'social-button': {
    slug: 'social-button',
    title: "SocialButton",
    description: "Individual branded social button with official network colors and icons.",
    category: "Social & Business",
    keywords: ["SocialButton","SocialButton component","React component","Tailwind CSS","Deneb UI","Social & Business","visual-first","storefront UI","headless e-commerce"],
  },
  'hero': {
    slug: 'hero',
    title: "Hero",
    description: "Centered and split hero banner sections with high-impact headline, glowing CTAs, and commerce actions.",
    category: "Storefront Sections",
    keywords: ["Hero","Hero component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'service-card': {
    slug: 'service-card',
    title: "ServiceCard",
    description: "Service package card with rate label, feature checkmark list, image thumbnail, and quote action.",
    category: "Storefront Sections",
    keywords: ["ServiceCard","ServiceCard component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'pricing-card': {
    slug: 'pricing-card',
    title: "PricingCard",
    description: "Tiered subscription and pricing plan card with feature checkmarks and highlight badges.",
    category: "Storefront Sections",
    keywords: ["PricingCard","PricingCard component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'testimonial-card': {
    slug: 'testimonial-card',
    title: "TestimonialCard",
    description: "Customer review card with 5-star ratings, avatar, customer name, and purchased product note.",
    category: "Storefront Sections",
    keywords: ["TestimonialCard","TestimonialCard component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'faq-accordion': {
    slug: 'faq-accordion',
    title: "FAQAccordion",
    description: "Smooth animated expandable accordion for FAQs, policies, and storefront documentation.",
    category: "Storefront Sections",
    keywords: ["FAQAccordion","FAQAccordion component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'announcement-bar': {
    slug: 'announcement-bar',
    title: "AnnouncementBar",
    description: "Top promotional ribbon for store announcements, flash sales, coupon codes, and free shipping thresholds.",
    category: "Storefront Sections",
    keywords: ["AnnouncementBar","AnnouncementBar component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'category-pills': {
    slug: 'category-pills',
    title: "CategoryPills",
    description: "Horizontal scrollable category filter pills with active indicator states for e-commerce catalogs.",
    category: "Storefront Sections",
    keywords: ["CategoryPills","CategoryPills component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'contact-form': {
    slug: 'contact-form',
    title: "ContactForm",
    description: "Lead generation and customer inquiry form with validated fields, accessible inputs, and visual editing bindings.",
    category: "Storefront Sections",
    keywords: ["ContactForm","ContactForm component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'navbar': {
    slug: 'navbar',
    title: "Navbar",
    description: "Glassmorphism storefront header with logo, desktop links, mobile drawer sheet, search, and cart triggers.",
    category: "Storefront Sections",
    keywords: ["Navbar","Navbar component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'footer': {
    slug: 'footer',
    title: "Footer",
    description: "Multi-column storefront footer with brand description, navigation links, policy links, and trust badges.",
    category: "Storefront Sections",
    keywords: ["Footer","Footer component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'site-data-provider': {
    slug: 'site-data-provider',
    title: "SiteDataProvider",
    description: "Headless state engine connecting Fivora API and live window postMessage updates to storefront components without page reloads.",
    category: "Data & State Engine",
    keywords: ["SiteDataProvider","SiteDataProvider component","React component","Tailwind CSS","Deneb UI","Data & State Engine","visual-first","storefront UI","headless e-commerce"],
  },
  'theme-styles': {
    slug: 'theme-styles',
    title: "ThemeStyles",
    description: "Runtime CSS custom properties injector for dynamic color palettes, typography, and border radii with pre-configured industry presets.",
    category: "Data & State Engine",
    keywords: ["ThemeStyles","ThemeStyles component","React component","Tailwind CSS","Deneb UI","Data & State Engine","visual-first","storefront UI","headless e-commerce"],
  },
  'use-products': {
    slug: 'use-products',
    title: "useProducts",
    description: "React hook to cleanly retrieve products from siteData with automatic backend rehydration from api.catalogUrl and real-time visual editor synchronization.",
    category: "Data & Theme Engine",
    keywords: ["useProducts","useProducts component","React component","Tailwind CSS","Deneb UI","Data & Theme Engine","visual-first","storefront UI","headless e-commerce"],
  },
  'use-site-api': {
    slug: 'use-site-api',
    title: "useSiteApi",
    description: "Hook providing direct typed access to official Fivora backend endpoints configured in site-data.json for custom API requests and form submissions.",
    category: "Data & Theme Engine",
    keywords: ["useSiteApi","useSiteApi component","React component","Tailwind CSS","Deneb UI","Data & Theme Engine","visual-first","storefront UI","headless e-commerce"],
  },
  'use-site-catalog': {
    slug: 'use-site-catalog',
    title: "useSiteCatalog",
    description: "Consolidated hook returning products, services, project identity, site instance, and API configuration in a single reactive call.",
    category: "Data & Theme Engine",
    keywords: ["useSiteCatalog","useSiteCatalog component","React component","Tailwind CSS","Deneb UI","Data & Theme Engine","visual-first","storefront UI","headless e-commerce"],
  },
  'product-detail': {
    slug: 'product-detail',
    title: "ProductDetail",
    description: "An elite single product showcase with multi-angle gallery, live size & color selectors, direct WhatsApp order CTA, and Fivora visual editing synchronization.",
    category: "Storefront Sections",
    keywords: ["ProductDetail","ProductDetail component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'platform-product-detail': {
    slug: 'platform-product-detail',
    title: "PlatformProductDetail",
    description: "The safe product-page controller for static storefronts. It reads the stable query ID, resolves live SiteData, retries the catalog API, and owns loading, error, and not-found states.",
    category: "Storefront Sections",
    keywords: ["PlatformProductDetail","PlatformProductDetail component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'product-quickview': {
    slug: 'product-quickview',
    title: "ProductQuickView",
    description: "Instant lightbox inspection modal for products with thumbnail switcher, bounds-protected quantity counter, and live visual editing.",
    category: "Storefront Sections",
    keywords: ["ProductQuickView","ProductQuickView component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'product-grid': {
    slug: 'product-grid',
    title: "ProductGrid",
    description: "Responsive commerce catalog grid with live backend search, debounced input, smart multi-variant pagination (numbers, simple, load-more), category filter tabs, strict empty-state preservation, and configurable columns per device. Includes quick-view trigger.",
    category: "Storefront Sections",
    keywords: ["ProductGrid","ProductGrid component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce","search bar","backend search","pagination","load more"],
  },
  'customer-reviews': {
    slug: 'customer-reviews',
    title: "CustomerReviews",
    description: "High-converting social proof showcase with aggregate star score, verified buyer authentication tags, and rating filters.",
    category: "Storefront Sections",
    keywords: ["CustomerReviews","CustomerReviews component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'trust-badges': {
    slug: 'trust-badges',
    title: "TrustBadges",
    description: "Conversion-boosting security and guarantee strip featuring free shipping, SSL checkout, warranty, and returns badges.",
    category: "Storefront Sections",
    keywords: ["TrustBadges","TrustBadges component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'sticky-mobile-bar': {
    slug: 'sticky-mobile-bar',
    title: "StickyMobileBar",
    description: "Sticky bottom checkout and WhatsApp action bar for mobile devices, boosting mobile conversion rates.",
    category: "Storefront Sections",
    keywords: ["StickyMobileBar","StickyMobileBar component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'filter-sidebar': {
    slug: 'filter-sidebar',
    title: "FilterSidebar",
    description: "Faceted catalog filtering sidebar with category chips, price slider, and size swatches. Collapses behind a mobile toggle below 768px; always visible on tablet and desktop.",
    category: "E-Commerce",
    keywords: ["FilterSidebar","FilterSidebar component","React component","Tailwind CSS","Deneb UI","E-Commerce","visual-first","storefront UI","headless e-commerce"],
  },
  'google-feedback': {
    slug: 'google-feedback',
    title: "GoogleFeedback",
    description: "Official Google Customer Review card section with verified platform badge, aggregate star pill, live 1–5 star DOM synchronization, and responsive review cards.",
    category: "Storefront Sections",
    keywords: ["GoogleFeedback","GoogleFeedback component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'testimonial-section': {
    slug: 'testimonial-section',
    title: "TestimonialSection",
    description: "Editorial critic and connoisseur review showcase featuring large quotation typography, author credentials, accreditation tags, and synchronized star ratings.",
    category: "Storefront Sections",
    keywords: ["TestimonialSection","TestimonialSection component","React component","Tailwind CSS","Deneb UI","Storefront Sections","visual-first","storefront UI","headless e-commerce"],
  },
  'map': {
    slug: 'map',
    title: "Map",
    description: "Universal Google Maps responsive iframe embed with intelligent URL parsing for full iframe snippets, @lat,lng coordinates, place URLs, short links, and search queries.",
    category: "Location & Navigation",
    keywords: ["Map","Map component","React component","Tailwind CSS","Deneb UI","Location & Navigation","visual-first","storefront UI","headless e-commerce"],
  },
  'product-card': {
    slug: 'product-card',
    title: "ProductCard",
    description: "High-converting e-commerce product card with Sri Lankan Rupee (LKR) pricing, brand attribution, dual WhatsApp inquiry & Add to Cart actions, and Fivora visual editing synchronization.",
    category: "E-Commerce & Storefront",
    keywords: ["ProductCard","ProductCard component","React component","Tailwind CSS","Deneb UI","E-Commerce & Storefront","visual-first","storefront UI","headless e-commerce"],
  },
  'cart-drawer': {
    slug: 'cart-drawer',
    title: "CartDrawer",
    description: "Interactive slide-over cart drawer with real-time state persistence, LKR currency formatting, quantity controls, and one-click unified WhatsApp checkout compiling all cart products into a single order chat message.",
    category: "E-Commerce & Storefront",
    keywords: ["CartDrawer","CartDrawer component","React component","Tailwind CSS","Deneb UI","E-Commerce & Storefront","visual-first","storefront UI","headless e-commerce"],
  },
  'editable-section': {
    slug: 'editable-section',
    title: "EditableSection",
    description: "Dynamic layout section container standardizing responsive vertical padding, 1-click move up/down section reordering (order), instant centering, and section deletion/hiding with strict data-design-section compliance.",
    category: "Storefront Sections",
    keywords: ["EditableSection", "section", "reorder", "center", "hidden", "layout", "blueprint", "Fivora", "Deneb UI"],
  },
  'section': {
    slug: 'section',
    title: "Section",
    description: "Standardized semantic section container with 1-click move up/down section reordering (CSS order), instant centering, and safe hiding (display: none) with 100% Fivora visual blueprint contract compliance.",
    category: "Core Primitives",
    keywords: ["Section", "EditableSection", "layout", "reorder", "center", "hidden", "blueprint", "Fivora", "Deneb UI"],
  },
};
